# Generated by Django 3.2 on 2021-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='localizacao',
            field=models.CharField(max_length=200),
        ),
    ]
