# Generated by Django 3.2 on 2021-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=7, null=True)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('sigla_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
    ]
