# Generated by Django 3.2 on 2021-04-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_municipios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('sigla_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('nm_regiao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
    ]
