# Generated by Django 3.2 on 2021-04-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
